[package]
name = "ch-commands"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true

[dependencies]
ch-common.workspace = true
ch-transport.workspace = true
ch-store.workspace = true
anyhow.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
russh.workspace = true
russh-keys.workspace = true
rustyline.workspace = true
async-trait.workspace = true